### ISSUE TITLE
你好，我配置了好像没有生效，是哪里出错了吗？

### ISSUE THREAD

**Issue by lijinshanmx** [tacesrever/frida-tsplugin#1]
![image](https://user-images.githubusercontent.com/6552340/78269843-b138d200-753c-11ea-95f1-0c67b4ccaefc.png)
![image](https://user-images.githubusercontent.com/6552340/78269988-d75e7200-753c-11ea-9d5b-0adec4555bbb.png)
![image](https://user-images.githubusercontent.com/6552340/78270008-e04f4380-753c-11ea-824f-2bf6d77ba4e4.png)

**Comment by lijinshanmx** [comment]
我用的是https://github.com/oleavr/frida-agent-example，这个demo框架，里面编译好像是frida-compile，是不是不会触发 tsconfig.json里面的plugins啊，还有插件目录应该是编译后的dist目录吧frida-tsplugin/dist。我该怎么设置才能用到自动提示呢？

**Comment by tacesrever** [comment]
后面不用跟着dist, 因为它识别的是frida-tsplugin目录下的package.json, 里面配置了main为dist/index.js  
不过我试了下配置为dist应该也可以生效的, 运行过electron-rebuild了吗
如果运行过了还是不行, 参考[tsserver logging](https://github.com/microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29#logging), 可以增加一个环境变量TSS_LOG, 内容为-level verbose -logToFile true -file path_to_logfile之后再试一下, 能看到一些日志信息

**Comment by lijinshanmx** [comment]
好的，我去试下，如果你能编写个详细的使用文档，包括插件编译和插件配置，我觉得会更好，应该有很多人会使用这个库。

**Comment by lijinshanmx** [comment]
![image](https://user-images.githubusercontent.com/6552340/78417515-7a121000-7665-11ea-8694-dfc7a1ff3156.png)

**Comment by lijinshanmx** [comment]
运行不成功，可能是我对环境配置太陌生了，我是照着论坛上你发的帖子运行的，可能哪里我配置出错了。。

**Comment by lijinshanmx** [comment]
如果有空的话，能帮我调一下吗？我的QQ:1919437986，十分感谢~ 另外，如果可以，我可以帮你推广一波你的这个插件，在我的网站上: https://gank.io

**Comment by lijinshanmx** [comment]
解决方法：
安装完npm i java 之后，进入到node_modules/_java@0.12.1@java/目录中 执行下面两个命令。
1、node-gyp rebuild --target=7.1.11 --dist-url=https://www.electronjs.org/headers --build-from-source
2、node postInstall.js
以编译出node modules version 相匹配的 node java.

**Comment by lijinshanmx** [comment]
![image](https://user-images.githubusercontent.com/6552340/78424025-389d5700-769d-11ea-9efe-4d6456d84e05.png)
成功以后的效果图，如果能自动补全 implemention = function(var1..)参数就更智能了，【手动点赞👍】

**Comment by SeeFlowerX** [comment]
楼主可以单独写个使用教程吗？

按README配置后，frida-agent-example也配置了plugins部分

但是vscode还是没有提示，只有Java相关的

访问本地的这个接口，有明确的返回

http://127.0.0.1:28042/getJavaClassInfo?className=java.lang.String

另外plugins添加了日志，然后日志结果显示只有一个plugin loaded

软件配置等

环境 win10

vscode

```bash
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:57:08.739Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT ia32 10.0.19041
```

node v14.15.0

frida 14.0.0 14.2.13 14.2.15 均测试过
